# Generated by Django 2.0.5 on 2018-05-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanager', '0002_auto_20180511_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='user_id',
        ),
    ]
