# Generated by Django 2.0.5 on 2018-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanager', '0004_auto_20180511_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='battery_number',
            field=models.IntegerField(default=0, verbose_name='Numer baterii'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='battery',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='battery',
            name='is_on',
            field=models.BooleanField(default=True, verbose_name='Włączona'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nazwa pojazdu'),
        ),
    ]
