# Generated by Django 2.0.5 on 2018-05-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanager', '0006_remove_battery_battery_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='battery_number',
            field=models.IntegerField(default=0, verbose_name='Numer baterii'),
            preserve_default=False,
        ),
    ]
