# Generated by Django 2.0.5 on 2018-05-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiclemanager', '0008_auto_20180513_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Numer ID'),
        ),
    ]
